function DesignerScene(){ return
[
	{
		"name":"initialStateNodeTemplate",
		"xPosition": 115,
		"yPosition": 110,
		"xAnchorPosition": 0.5,
		"yAnchorPosition": 0.5,
		"xScale": 1,
		"yScale": 1,
		"radius": 50,
		"enabled": true,
		"dragDrop":true,
		"animationStartName":"swithUnselectedInitialState",
		"type": "sprite | animation",
		"shape":"circle"
	},
	{
		"name":"stateNodeTemplate",
		"xPosition": 110,
		"yPosition": 260,
		"xAnchorPosition": 0.5,
		"yAnchorPosition": 0.5,
		"xScale": 1,
		"yScale": 1,
		"enabled": true,
		"dragDrop":true,
		"animationStartName":"switchUnselectedState",
		"type": "sprite | animation",
		"shape":"rectangle"
	},
	{
		"name":"stateNodeLinkTemplate",
		"xPosition": 40,
		"yPosition": 400,
		"xAnchorPosition": 0,
		"yAnchorPosition": 0.5,
		"startNode":"",
		"endNode":"",
		"xScale": 0.4,
		"yScale": 1,
		"enabled": true,
		"dragDrop":true,
		"animationStartName":"switchUnselectedStateNodeLink",
		"type": "sprite | animation",
		"shape":"line",
		"width":"150",
		"height":"15"
	},
	{
		"name":"finalStateNodeTemplate",
		"xPosition": 115,
		"yPosition": 550,
		"xAnchorPosition": 0.5,
		"yAnchorPosition": 0.5,
		"xScale": 1,
		"yScale": 1,
		"radius": 50,
		"enabled": true,
		"dragDrop":true,
		"animationStartName":"switchUnselectedFinalState",
		"type": "sprite | animation",
		"shape":"circle"
	},
	{
        "enabled": true,
        "height": 600,
        "xAnchorPosition": -1,
		"yAnchorPosition": -1,
        "isStatic": true,
        "name": "diagramMenu",
        "width": 200,
        "xPosition": 10,
        "yPosition": 10,
        "xScale": 1,
        "yScale": 1,
        "type": "image",
		"shape":"circle",
		"width":"200",
		"height":"600"
    },
	{
		"name":"contextLoader",
		"xPosition": 500,
		"yPosition": 500,
		"xAnchorPosition": 0.5,
		"yAnchorPosition": 0.5,
		"xScale": 1,
		"yScale": 1,
		"radius": 50,
		"enabled": true,
		"dragDrop":false,
		"type": "sprite | animation",
		"shape":"circle"
	},
	{
		"name":"publish",
		"xPosition": 400,
		"yPosition": 40,
		"xAnchorPosition": -1,
		"yAnchorPosition": -1,
		"xScale": 1,
		"yScale": 1,
		"enabled": true,
		"type": "sprite | animation",
		"shape":"rectangle",
		"width":"181",
		"height":"44"
	},
	{
		"name":"preview",
		"xPosition": 600,
		"yPosition": 40,
		"xAnchorPosition": -1,
		"yAnchorPosition": -1,
		"xScale": 1,
		"yScale": 1,
		"enabled": true,
		"type": "sprite | animation",
		"shape":"rectangle",
		"width":"181",
		"height":"44"
	},
	{
		"name":"stateNodeLinkArrowTemplate",
		"xPosition": 0,
		"yPosition": 0,
		"xAnchorPosition": 1,
		"yAnchorPosition": 0.5,
		"startNode":"",
		"endNode":"",
		"xScale": 1,
		"yScale": 1,
		"enabled": true,
		"dragDrop":false,
		"animationStartName":"switchUnselectedStateNodeLinkArrow",
		"type": "sprite | animation",
		"shape":"arrow",
		"width":"14.5",
		"height":"15",
		"visible":false
	}
]
}
module.exports=DesignerScene